import os.path

APP_VER="1.0.0"

EXT_DISK_MOUNTPOINT="/mnt/hc-data"
EXT_ROOT=EXT_DISK_MOUNTPOINT

APP_ROOT=os.path.dirname(__file__)
QML_MAIN=os.path.join(APP_ROOT, "qml", "main.qml")
QML_ERROR=os.path.join(APP_ROOT, "qml", "error.qml")
QML_FIRSTRUN=os.path.join(APP_ROOT, "qml", "firstrun.qml")
HC_CONFIG=os.path.join(APP_ROOT, "config", "HomeControl.conf")
DOORBELL_WAV=os.path.join(APP_ROOT, "res", "wav", "doorbell.wav")
CHRONYD_BIN=os.path.join(APP_ROOT, "res", "bin", "chronyd")
CHRONYD_CONF=os.path.join(APP_ROOT, "config", "chrony.conf")

DEFAULT_DATA_REFRESH_RATE=10
DEFAULT_DB_DATA_INSERT_RATE=60
DEFAULT_NIGHT_TIME_RANGE=(5, 18)
DEFAULT_DISPLAY_TIMEOUT=60

DOORSTATION_IDVENDOR=0x16c0
DOORSTATION_IDPRODUCT=0x05df

DS1302_SCLKPIN=10
DS1302_CEPIN=11
DS1302_IOPIN=9

DS18B20_SENSORPIN=26

VL53L0X_I2CADDRESS=0x29

GPIO_NUM_DISPDEC=22
GPIO_NUM_DISPINC=4
GPIO_NUM_DISPPWR=27
GPIO_NUM_LOCK_REL=15
GPIO_NUM_EXTBELL=6

GPIO_BUT_BOUNCETIME=250

NETIF_ETH="eth0"
NETIF_WIFI="wlan0"

ACARD_HANDSET="Device"
ACARD_DOORSTATION="Device_1"
ACARD_HDMI="vc4hdmi0"

ACARD_EXT_CONTROL_SPEAKER="Speaker"
ACARD_EXT_CONTROL_MIC="Mic"
ACARD_INT_CONTROL_SPEAKER="PCM"

VOL_STEPS=10

DISP_BRIGHTNESS_STEPS=10

HANDSET_TAKE_TH=60

WEB_PORT=80
WEB_BIND_ADDR="0.0.0.0"

FTP_PORT=21
FTP_BIND_ADDR="0.0.0.0"
